version: 2

dist: build

before:
  hooks:
    - cp scripts/install-man-page.sh .

builds:
  - id: yq
    binary: yq_{{ .Os }}_{{ .Arch }}
    flags:
      - -trimpath
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - loong64
      - mips64le
      - ppc64le
      - s390x
      - riscv64
    no_unique_dist_dir: true

archives:
  - formats: [ 'tar.gz' ]
    name_template: "{{ .Binary }}"
    wrap_in_directory: false
    files:
      - install-man-page.sh
      - yq.1
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
  split: false

changelog:
  use: github
  sort: '' # use the output of `git log` as is
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^tests:'
      - '^chore:'
      - '^Merge pull request'

release:
  github:
    owner: loong64
    name: yq